### ISSUE TITLE
Счупена булева логика при поздравителното съобщение за нерегистрирани

### ISSUE THREAD

**Issue by bmanolov** [wikimedia-bg/wikipedia-ui#3]
Поздравителното съобщение за нерегистрирани, намиращо се в [Common.js](https://bg.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D0%B8%D1%8F%D0%A3%D0%B8%D0%BA%D0%B8:Common.js), явно не работи от много години заради счупена проверка. Следния код винаги връща `false`:

```javascript
mw.config.get("wgRestrictionEdit") === []
```

**Comment by kerberizer** [comment]
Fixed by 424af40a61bc3bff3dfed9207aa7e77b1dbe569b
