### ISSUE TITLE
Замяна на collapsible с mw-collapsible

### ISSUE THREAD

**Issue by bmanolov** [wikimedia-bg/wikipedia-ui#5]
От много години е въведен класа `mw-collapsible`, който се поддържа от модула [jquery.makeCollapsible](https://www.mediawiki.org/wiki/ResourceLoader/Core_modules#jquery.makeCollapsible). Време е да спрем да използваме обявения за остарял клас `collapsible` и да преминем към `mw-collapsible`.

**Comment by petar-petrov-w** [comment]
Това е за заместване из статиите с бот, нали?  Не виждам много какво да се направи по js/css освен да се изтрие ` createCollapseButtons()` след това.
https://github.com/wikimedia-bg/wikipedia-ui/blob/f0ac99def0ffbd067e5315de871414438b840ab0/Common.js#L307

**Comment by bmanolov** [comment]
Тук имах предвид напасването на Common.js и на съответните модули и шаблони. Повечето ще е ръчна работа.

`createCollapseButtons` ще се махне, но трябва да се добави една врътка, за да остане поддръжката на класа `autocollapse`.

Ще направя нужните промени, като пуснем тестово уики, защото не ми се играе с тестване в Уикипедия.
